networks:
  labnet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/24
services:
  attacker:
    build: ./attacker
    container_name: attacker
    networks:
      labnet:
        ipv4_address: 172.20.0.186
    tty: true
    volumes:
    - ./shared:/shared
  snort:
    build: ./snort
    container_name: snort
    networks:
      labnet:
        ipv4_address: 172.20.0.10
    tty: true
    volumes:
    - ./shared:/shared
